apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd
  namespace: staging-system
  labels:
    app: cicd
spec:
  replicas: 1
  template:
    metadata:
      name: cicd
      labels:
        app: cicd
    spec:
      imagePullSecrets:
        - name: dockersecret
      containers:
        - name: cicd2
          image: techieiq/cicd
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: cicd
