apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd2
  namespace: staging-system
  labels:
    app: cicd2
spec:
  replicas: 1
  template:
    metadata:
      name: cicd2
      labels:
        app: cicd2
    spec:
      imagePullSecrets:
        - name: dockersecret
      containers:
        - name: cicd2
          image: techieiq/cicd2
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: cicd2
