commonLabels:
  app: cicd2
resources:
- deployment.yaml
- service.yaml
- destination-rule.yaml
- virtual-svc.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: cicd2
  newName: techieiq/cicd2
  newTag: d3997a3263c91c1a101b933d98efa9e3ae3431ba
