apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cicd
spec:
  hosts:
    - cicd-one
  http:
    - route:
        - destination:
            host: cicd
            subset: v1