apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cicd2
spec:
  hosts:
    - cicd2
  http:
    - route:
        - destination:
            host: cicd2
            subset: v1